defmodule Mezzanine.OpsDomain.Repo.Migrations.Phase11SurfacesAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:placement_profiles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :program_id,
        references(:programs,
          column: :id,
          name: "placement_profiles_program_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:profile_id, :text, null: false)
      add(:strategy, :text, null: false)
      add(:target_selector, :map, null: false, default: %{})
      add(:runtime_preferences, :map, null: false, default: %{})
      add(:workspace_policy, :map, null: false, default: %{})
      add(:metadata, :map, null: false, default: %{})
      add(:status, :text, null: false, default: "draft")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:placement_profiles, [:tenant_id, :program_id, :profile_id],
             name: "placement_profiles_unique_profile_per_program_index"
           )
  end

  def down do
    drop(constraint(:placement_profiles, "placement_profiles_program_id_fkey"))

    drop_if_exists(
      unique_index(:placement_profiles, [:tenant_id, :program_id, :profile_id],
        name: "placement_profiles_unique_profile_per_program_index"
      )
    )

    drop(table(:placement_profiles))
  end
end
