defmodule Mezzanine.OpsDomain.Repo.Migrations.Phase7ExecutionReviewControl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:waivers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:review_unit_id, :uuid, null: false)
      add(:work_object_id, :uuid, null: false)
      add(:reason, :text, null: false)
      add(:granted_by, :text, null: false)
      add(:expires_at, :utc_datetime)
      add(:conditions, {:array, :text}, null: false, default: [])
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:timeline_projections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "timeline_projections_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:timeline, {:array, :map}, null: false, default: [])
      add(:last_event_at, :utc_datetime)
      add(:projected_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:timeline_projections, [:tenant_id, :work_object_id],
             name: "timeline_projections_unique_work_object_projection_index"
           )

    create table(:runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:run_series_id, :uuid, null: false)
      add(:attempt, :bigint, null: false, default: 1)
      add(:status, :text, null: false, default: "pending")
      add(:runtime_profile, :map, null: false, default: %{})
      add(:placement_profile_id, :uuid)
      add(:grant_profile, :map, null: false, default: %{})
      add(:started_at, :utc_datetime)
      add(:completed_at, :utc_datetime)
      add(:result_summary, :text)
      add(:raw_runtime_ref, :text)
      add(:token_usage, :map, null: false, default: %{})
      add(:evidence_bundle_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:run_series, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:runs) do
      modify(
        :run_series_id,
        references(:run_series,
          column: :id,
          name: "runs_run_series_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:run_series) do
      add(:tenant_id, :text, null: false)

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "run_series_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:sequence, :bigint, null: false, default: 1)
      add(:status, :text, null: false, default: "active")

      add(
        :current_run_id,
        references(:runs,
          column: :id,
          name: "run_series_current_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:control_session_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:run_grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :run_id,
        references(:runs,
          column: :id,
          name: "run_grants_run_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:grant_kind, :text, null: false)
      add(:scope, :map, null: false, default: %{})
      add(:approval_class, :text)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:run_artifacts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :run_id,
        references(:runs,
          column: :id,
          name: "run_artifacts_run_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:kind, :text, null: false)
      add(:ref, :text, null: false)
      add(:metadata, :map, null: false, default: %{})
      add(:status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:review_units, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:waivers) do
      modify(
        :review_unit_id,
        references(:review_units,
          column: :id,
          name: "waivers_review_unit_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "waivers_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:review_units) do
      add(:tenant_id, :text, null: false)

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "review_units_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :run_id,
        references(:runs,
          column: :id,
          name: "review_units_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:review_kind, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:required_by, :utc_datetime)
      add(:decision_profile, :map, null: false, default: %{})
      add(:evidence_bundle_id, :uuid)
      add(:reviewer_actor, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:review_decisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :review_unit_id,
        references(:review_units,
          column: :id,
          name: "review_decisions_review_unit_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:decision, :text, null: false)
      add(:actor_kind, :text)
      add(:actor_ref, :text)
      add(:reason, :text)
      add(:payload, :map, null: false, default: %{})
      add(:decided_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:operator_interventions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:control_session_id, :uuid, null: false)
      add(:operator_ref, :text, null: false)
      add(:intervention_kind, :text, null: false)
      add(:payload, :map, null: false, default: %{})
      add(:occurred_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:evidence_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:evidence_bundle_id, :uuid, null: false)
      add(:kind, :text, null: false)
      add(:ref, :text, null: false)
      add(:metadata, :map, null: false, default: %{})
      add(:status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:evidence_bundles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:runs) do
      modify(
        :evidence_bundle_id,
        references(:evidence_bundles,
          column: :id,
          name: "runs_evidence_bundle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:review_units) do
      modify(
        :evidence_bundle_id,
        references(:evidence_bundles,
          column: :id,
          name: "review_units_evidence_bundle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:evidence_items) do
      modify(
        :evidence_bundle_id,
        references(:evidence_bundles,
          column: :id,
          name: "evidence_items_evidence_bundle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:evidence_bundles) do
      add(:tenant_id, :text, null: false)

      add(
        :program_id,
        references(:programs,
          column: :id,
          name: "evidence_bundles_program_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "evidence_bundles_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :run_id,
        references(:runs,
          column: :id,
          name: "evidence_bundles_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:status, :text, null: false, default: "assembling")
      add(:summary, :text)
      add(:evidence_manifest, :map, null: false, default: %{})
      add(:completeness_status, :map, null: false, default: %{})
      add(:assembled_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:escalations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :review_unit_id,
        references(:review_units,
          column: :id,
          name: "escalations_review_unit_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "escalations_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:reason, :text)
      add(:escalated_by, :text)
      add(:assigned_to, :text)
      add(:priority, :text)
      add(:resolved_at, :utc_datetime)
      add(:status, :text, null: false, default: "open")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:control_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:run_series) do
      modify(
        :control_session_id,
        references(:control_sessions,
          column: :id,
          name: "run_series_control_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:operator_interventions) do
      modify(
        :control_session_id,
        references(:control_sessions,
          column: :id,
          name: "operator_interventions_control_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:control_sessions) do
      add(:tenant_id, :text, null: false)

      add(
        :program_id,
        references(:programs,
          column: :id,
          name: "control_sessions_program_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "control_sessions_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:status, :text, null: false, default: "active")
      add(:current_mode, :text, null: false, default: "normal")
      add(:active_override_set, :map, null: false, default: %{})
      add(:last_operator_action_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:control_sessions, [:tenant_id, :work_object_id],
             name: "control_sessions_unique_work_object_session_index"
           )

    create table(:audit_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :program_id,
        references(:programs,
          column: :id,
          name: "audit_events_program_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "audit_events_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :run_id,
        references(:runs,
          column: :id,
          name: "audit_events_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :review_unit_id,
        references(:review_units,
          column: :id,
          name: "audit_events_review_unit_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:event_kind, :text, null: false)
      add(:actor_kind, :text)
      add(:actor_ref, :text)
      add(:payload, :map, null: false, default: %{})
      add(:occurred_at, :utc_datetime, null: false)
    end
  end

  def down do
    drop(constraint(:audit_events, "audit_events_program_id_fkey"))

    drop(constraint(:audit_events, "audit_events_work_object_id_fkey"))

    drop(constraint(:audit_events, "audit_events_run_id_fkey"))

    drop(constraint(:audit_events, "audit_events_review_unit_id_fkey"))

    drop(table(:audit_events))

    drop(constraint(:control_sessions, "control_sessions_program_id_fkey"))

    drop(constraint(:control_sessions, "control_sessions_work_object_id_fkey"))

    drop_if_exists(
      unique_index(:control_sessions, [:tenant_id, :work_object_id],
        name: "control_sessions_unique_work_object_session_index"
      )
    )

    alter table(:control_sessions) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_operator_action_at)
      remove(:active_override_set)
      remove(:current_mode)
      remove(:status)
      remove(:work_object_id)
      remove(:program_id)
      remove(:tenant_id)
    end

    drop(constraint(:operator_interventions, "operator_interventions_control_session_id_fkey"))

    alter table(:operator_interventions) do
      modify(:control_session_id, :uuid)
    end

    drop(constraint(:run_series, "run_series_control_session_id_fkey"))

    alter table(:run_series) do
      modify(:control_session_id, :uuid)
    end

    drop(table(:control_sessions))

    drop(constraint(:escalations, "escalations_review_unit_id_fkey"))

    drop(constraint(:escalations, "escalations_work_object_id_fkey"))

    drop(table(:escalations))

    drop(constraint(:evidence_bundles, "evidence_bundles_program_id_fkey"))

    drop(constraint(:evidence_bundles, "evidence_bundles_work_object_id_fkey"))

    drop(constraint(:evidence_bundles, "evidence_bundles_run_id_fkey"))

    alter table(:evidence_bundles) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:assembled_at)
      remove(:completeness_status)
      remove(:evidence_manifest)
      remove(:summary)
      remove(:status)
      remove(:run_id)
      remove(:work_object_id)
      remove(:program_id)
      remove(:tenant_id)
    end

    drop(constraint(:evidence_items, "evidence_items_evidence_bundle_id_fkey"))

    alter table(:evidence_items) do
      modify(:evidence_bundle_id, :uuid)
    end

    drop(constraint(:review_units, "review_units_evidence_bundle_id_fkey"))

    alter table(:review_units) do
      modify(:evidence_bundle_id, :uuid)
    end

    drop(constraint(:runs, "runs_evidence_bundle_id_fkey"))

    alter table(:runs) do
      modify(:evidence_bundle_id, :uuid)
    end

    drop(table(:evidence_bundles))

    drop(table(:evidence_items))

    drop(table(:operator_interventions))

    drop(constraint(:review_decisions, "review_decisions_review_unit_id_fkey"))

    drop(table(:review_decisions))

    drop(constraint(:review_units, "review_units_work_object_id_fkey"))

    drop(constraint(:review_units, "review_units_run_id_fkey"))

    alter table(:review_units) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:reviewer_actor)
      remove(:evidence_bundle_id)
      remove(:decision_profile)
      remove(:required_by)
      remove(:status)
      remove(:review_kind)
      remove(:run_id)
      remove(:work_object_id)
      remove(:tenant_id)
    end

    drop(constraint(:waivers, "waivers_review_unit_id_fkey"))

    drop(constraint(:waivers, "waivers_work_object_id_fkey"))

    alter table(:waivers) do
      modify(:work_object_id, :uuid)
      modify(:review_unit_id, :uuid)
    end

    drop(table(:review_units))

    drop(constraint(:run_artifacts, "run_artifacts_run_id_fkey"))

    drop(table(:run_artifacts))

    drop(constraint(:run_grants, "run_grants_run_id_fkey"))

    drop(table(:run_grants))

    drop(constraint(:run_series, "run_series_work_object_id_fkey"))

    drop(constraint(:run_series, "run_series_current_run_id_fkey"))

    alter table(:run_series) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:control_session_id)
      remove(:current_run_id)
      remove(:status)
      remove(:sequence)
      remove(:work_object_id)
      remove(:tenant_id)
    end

    drop(constraint(:runs, "runs_run_series_id_fkey"))

    alter table(:runs) do
      modify(:run_series_id, :uuid)
    end

    drop(table(:run_series))

    drop(table(:runs))

    drop(constraint(:timeline_projections, "timeline_projections_work_object_id_fkey"))

    drop_if_exists(
      unique_index(:timeline_projections, [:tenant_id, :work_object_id],
        name: "timeline_projections_unique_work_object_projection_index"
      )
    )

    drop(table(:timeline_projections))

    drop(table(:waivers))
  end
end
