defmodule Mezzanine.OpsDomain.Repo.Migrations.InitOpsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:work_objects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:program_id, :uuid, null: false)
      add(:work_class_id, :uuid, null: false)
      add(:external_ref, :text)
      add(:title, :text, null: false)
      add(:description, :text)
      add(:status, :text, null: false, default: "pending")
      add(:priority, :bigint, null: false, default: 50)
      add(:source_kind, :text)
      add(:payload, :map, null: false, default: %{})
      add(:normalized_payload, :map, null: false, default: %{})
      add(:current_plan_id, :uuid)
      add(:blocked_by_work_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:work_objects, [:program_id, :external_ref],
             name: "work_objects_unique_external_ref_per_program_index"
           )

    create table(:work_classes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)
      add(:program_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:kind, :text, null: false)
      add(:intake_schema, :map, null: false, default: %{})
      add(:policy_bundle_ref, :text)
      add(:default_review_profile, :map, null: false, default: %{})
      add(:default_run_profile, :map, null: false, default: %{})
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:work_classes, [:program_id, :name],
             name: "work_classes_unique_name_per_program_index"
           )

    create table(:programs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:work_objects) do
      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_objects_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :work_class_id,
        references(:work_classes,
          column: :id,
          name: "work_objects_work_class_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:work_classes) do
      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_classes_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:programs) do
      add(:tenant_id, :text, null: false)
      add(:slug, :text, null: false)
      add(:name, :text, null: false)
      add(:status, :text, null: false, default: "draft")
      add(:product_family, :text)
      add(:configuration, :map, null: false, default: %{})
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:programs, [:tenant_id, :slug],
             name: "programs_unique_slug_per_tenant_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:programs, [:tenant_id, :slug], name: "programs_unique_slug_per_tenant_index")
    )

    alter table(:programs) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:configuration)
      remove(:product_family)
      remove(:status)
      remove(:name)
      remove(:slug)
      remove(:tenant_id)
    end

    drop(constraint(:work_classes, "work_classes_program_id_fkey"))

    alter table(:work_classes) do
      modify(:program_id, :uuid)
    end

    drop(constraint(:work_objects, "work_objects_program_id_fkey"))

    drop(constraint(:work_objects, "work_objects_work_class_id_fkey"))

    alter table(:work_objects) do
      modify(:work_class_id, :uuid)
      modify(:program_id, :uuid)
    end

    drop(table(:programs))

    drop_if_exists(
      unique_index(:work_classes, [:program_id, :name],
        name: "work_classes_unique_name_per_program_index"
      )
    )

    drop(table(:work_classes))

    drop_if_exists(
      unique_index(:work_objects, [:program_id, :external_ref],
        name: "work_objects_unique_external_ref_per_program_index"
      )
    )

    drop(table(:work_objects))
  end
end
