defmodule Mezzanine.OpsDomain.Repo.Migrations.Phase8SchedulerRuntime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:work_objects) do
      add(:lease_owner, :text)
      add(:lease_expires_at, :utc_datetime)
    end
  end

  def down do
    alter table(:work_objects) do
      remove(:lease_expires_at)
      remove(:lease_owner)
    end
  end
end
