defmodule Mezzanine.OpsDomain.Repo.Migrations.Phase6Planning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:work_plans, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:tenant_id, :text, null: false)

      add(
        :work_object_id,
        references(:work_objects,
          column: :id,
          name: "work_plans_work_object_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:policy_bundle_id, :uuid)
      add(:version, :bigint, null: false, default: 1)
      add(:status, :text, null: false, default: "draft")
      add(:plan_payload, :map, null: false, default: %{})
      add(:derived_run_intents, {:array, :map}, null: false, default: [])
      add(:derived_review_intents, {:array, :map}, null: false, default: [])
      add(:derived_effect_intents, {:array, :map}, null: false, default: [])
      add(:derived_read_intents, {:array, :map}, null: false, default: [])
      add(:derived_notification_intents, {:array, :map}, null: false, default: [])
      add(:obligation_ids, {:array, :text}, null: false, default: [])
      add(:compiled_at, :utc_datetime)
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:work_plans, [:tenant_id, :work_object_id, :version],
             name: "work_plans_unique_version_per_work_object_index"
           )

    drop(constraint(:work_objects, "work_objects_work_class_id_fkey"))

    drop(constraint(:work_objects, "work_objects_program_id_fkey"))

    drop_if_exists(
      unique_index(:work_objects, [:program_id, :external_ref],
        name: "work_objects_unique_external_ref_per_program_index"
      )
    )

    create unique_index(:work_objects, [:tenant_id, :program_id, :external_ref],
             name: "work_objects_unique_external_ref_per_program_index"
           )

    alter table(:work_objects) do
      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_objects_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :work_class_id,
        references(:work_classes,
          column: :id,
          name: "work_objects_work_class_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :current_plan_id,
        references(:work_plans,
          column: :id,
          name: "work_objects_current_plan_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create index(:work_objects, [:tenant_id, :current_plan_id])

    alter table(:work_classes) do
      remove(:policy_bundle_ref)
    end

    drop(constraint(:work_classes, "work_classes_program_id_fkey"))

    alter table(:work_classes) do
      add(:policy_bundle_id, :uuid)
    end

    drop_if_exists(
      unique_index(:work_classes, [:program_id, :name],
        name: "work_classes_unique_name_per_program_index"
      )
    )

    create unique_index(:work_classes, [:tenant_id, :program_id, :name],
             name: "work_classes_unique_name_per_program_index"
           )

    drop_if_exists(
      unique_index(:programs, [:tenant_id, :slug], name: "programs_unique_slug_per_tenant_index")
    )

    create unique_index(:programs, [:tenant_id, :slug],
             name: "programs_unique_slug_per_tenant_index"
           )

    create table(:policy_bundles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:work_plans) do
      modify(
        :policy_bundle_id,
        references(:policy_bundles,
          column: :id,
          name: "work_plans_policy_bundle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:work_classes) do
      modify(
        :policy_bundle_id,
        references(:policy_bundles,
          column: :id,
          name: "work_classes_policy_bundle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_classes_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:policy_bundles) do
      add(:tenant_id, :text, null: false)

      add(
        :program_id,
        references(:programs,
          column: :id,
          name: "policy_bundles_program_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:name, :text, null: false)
      add(:version, :text, null: false)
      add(:policy_kind, :text, null: false, default: "workflow_md")
      add(:source_ref, :text, null: false, default: "inline")
      add(:body, :text, null: false)
      add(:config, :map, null: false, default: %{})
      add(:prompt_template, :text, null: false, default: "")
      add(:compiled_form, :map, null: false, default: %{})
      add(:status, :text, null: false, default: "compiled")
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:policy_bundles, [:tenant_id, :program_id, :name, :version],
             name: "policy_bundles_unique_version_per_program_index"
           )
  end

  def down do
    drop(constraint(:policy_bundles, "policy_bundles_program_id_fkey"))

    drop_if_exists(
      unique_index(:policy_bundles, [:tenant_id, :program_id, :name, :version],
        name: "policy_bundles_unique_version_per_program_index"
      )
    )

    alter table(:policy_bundles) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:status)
      remove(:compiled_form)
      remove(:prompt_template)
      remove(:config)
      remove(:body)
      remove(:source_ref)
      remove(:policy_kind)
      remove(:version)
      remove(:name)
      remove(:program_id)
      remove(:tenant_id)
    end

    drop(constraint(:work_classes, "work_classes_policy_bundle_id_fkey"))

    drop(constraint(:work_classes, "work_classes_program_id_fkey"))

    alter table(:work_classes) do
      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_classes_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(:policy_bundle_id, :uuid)
    end

    drop(constraint(:work_plans, "work_plans_policy_bundle_id_fkey"))

    alter table(:work_plans) do
      modify(:policy_bundle_id, :uuid)
    end

    drop(table(:policy_bundles))

    drop_if_exists(
      unique_index(:programs, [:tenant_id, :slug], name: "programs_unique_slug_per_tenant_index")
    )

    create unique_index(:programs, [:tenant_id, :slug],
             name: "programs_unique_slug_per_tenant_index"
           )

    drop_if_exists(
      unique_index(:work_classes, [:tenant_id, :program_id, :name],
        name: "work_classes_unique_name_per_program_index"
      )
    )

    create unique_index(:work_classes, [:program_id, :name],
             name: "work_classes_unique_name_per_program_index"
           )

    alter table(:work_classes) do
      remove(:policy_bundle_id)
    end

    alter table(:work_classes) do
      add(:policy_bundle_ref, :text)
    end

    drop_if_exists(index(:work_objects, [:tenant_id, :current_plan_id]))

    drop(constraint(:work_objects, "work_objects_program_id_fkey"))

    drop(constraint(:work_objects, "work_objects_work_class_id_fkey"))

    drop(constraint(:work_objects, "work_objects_current_plan_id_fkey"))

    alter table(:work_objects) do
      modify(:current_plan_id, :uuid)

      modify(
        :work_class_id,
        references(:work_classes,
          column: :id,
          name: "work_objects_work_class_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :program_id,
        references(:programs,
          column: :id,
          name: "work_objects_program_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop_if_exists(
      unique_index(:work_objects, [:tenant_id, :program_id, :external_ref],
        name: "work_objects_unique_external_ref_per_program_index"
      )
    )

    create unique_index(:work_objects, [:program_id, :external_ref],
             name: "work_objects_unique_external_ref_per_program_index"
           )

    drop(constraint(:work_plans, "work_plans_work_object_id_fkey"))

    drop_if_exists(
      unique_index(:work_plans, [:tenant_id, :work_object_id, :version],
        name: "work_plans_unique_version_per_work_object_index"
      )
    )

    drop(table(:work_plans))
  end
end
